import { ReactNode } from "react"
import type { Metadata } from "next"
import { Noto_Sans_JP } from "next/font/google"
import StyledComponentsRegistry from "@/shared/lib/styled-components-registry"
import "./assets/globals.css"

const notoSansJP = Noto_Sans_JP({ subsets: ["latin"], weight: ["400"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="ja">
      <body className={notoSansJP.className}>
        <StyledComponentsRegistry>{children}</StyledComponentsRegistry>
      </body>
    </html>
  )
}
